version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:8080
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER = YAM428
      - MARIADB_PASSWORD = 030718050
      - MARIADB_DATABASE = final
      
  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER = YAM428
      - MARIADB_PASSWORD = 030718050
      - MARIADB_DATABASE = final
      
  webserver:
    image: nginx
    ports:
      - 80:80
      - 443:443
      
